{{- if .Values.vcd.credentials }}
apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  name: image-distribution-operator-vcd-credentials
  namespace: {{ .Release.Namespace }}
stringData:
  credentials: |-
    {{- .Values.vcd.credentials | toYaml | nindent 4 }}
type: Opaque
{{- end }}
