{{- if .Values.vcd.locations }}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  name: image-distribution-operator-vcd-locations
  namespace: {{ .Release.Namespace }}
data:
  locations: |-
    {{- .Values.vcd.locations | toYaml | nindent 4 }}
{{- end }}
