apiVersion: v2
name: image-distribution-operator
description: A Helm chart to distribute the project image-distribution-operator
type: application
version: 0.7.0
appVersion: "0.7.0"
icon: https://s.giantswarm.io/app-icons/giantswarm/1/light.svg
annotations:
  io.giantswarm.application.team: "rocket"
